# this file is used to run a nextjs app with a mysql database

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:3000"
    volumes:
      - .:/app
      - /app/node_modules
  



