import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import "../../styles/theme.css";
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import '../../styles/componentsStyles/exampleCardFlex.module.css'
//import "primereact/resources/themes/lara-light-teal/theme.css";
//import 'primereact/resources/themes/lara-light-orange/theme.css';
import 'primereact/resources/themes/vela-orange/theme.css';


import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <PrimeReactProvider value={{ unstyled: true }}> */}
      <PrimeReactProvider >
        <body className={inter.className}>{children}</body>
      </PrimeReactProvider>
    </html>
  );
}
