import { NextUiProvider } from "@/providers/NextUiProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sistema Incidencias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUiProvider>
          <div className="">
            {/* <h1>layout padre</h1> */}
            {children}
          </div>
        </NextUiProvider>
      </body>
    </html>
  );
}
